name: Fetch and Process Proxy Lists

on:
  schedule:
    - cron: '10 16 * * *'  # 每天东八区凌晨00:10运行
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl wget
    - name: Initialize Go module and get dependencies
      run: |
        go mod init github.com/${{ github.repository }}
        go get golang.org/x/time/rate
    - name: Download Fofa-list
      run: |
        DOWNLOAD_URL=$(curl -s https://api.github.com/repos/Cl0udG0d/Fofa-hack/releases/latest | grep "browser_download_url.*fofa-hack_linux_amd64" | cut -d '"' -f 4)
        wget -O fofa $DOWNLOAD_URL
        chmod +x fofa

    - name: Run Fofa-list
      run: |
        mkdir -p /tmp/fofa_output
        ./fofa -k 'body="Sansui233"' -e 100 -on /tmp/fofa_output/domains
   
    - name: Count and display domains
      run: |
        DOMAIN_COUNT=$(wc -l < /tmp/fofa_output/domains.txt)
        echo "Total number of domains found: $DOMAIN_COUNT"

    - name: Process domains
      run: |
        mkdir -p output
        go run process_domains.go -input /tmp/fofa_output/domains.txt -output ./output
      env:
        ACTIONS_STEP_DEBUG: true

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/vmess_list.txt output/trojan_list.txt
        git commit -m "Update proxy lists" || echo "No changes to commit"
        git push

    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: execution-logs
        path: |
          /tmp/fofa_output/domains.txt
          ./output/vmess_list.txt
          ./output/trojan_list.txt
