name: Fetch and Process Proxy Lists

on:
  schedule:
    - cron: '10 16 * * *'  # 每天东八区凌晨00:10运行
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl wget

    - name: Download Fofa-list
      run: |
        DOWNLOAD_URL=$(curl -s https://api.github.com/repos/Cl0udG0d/Fofa-hack/releases/latest | grep "browser_download_url.*fofa-hack_linux_amd64" | cut -d '"' -f 4)
        wget -O fofa $DOWNLOAD_URL
        chmod +x fofa

    - name: Run Fofa-list
      run: |
        mkdir -p /tmp/fofa_output
        ./fofa -k 'body="Sansui233"' -e 500 -on /tmp/fofa_output/domains
    - name: Find and display domains.txt location
      run: |
        echo "Searching for domains.txt file..."
        DOMAINS_FILE=$(find / -name domains.txt 2>/dev/null)
        if [ -n "$DOMAINS_FILE" ]; then
          echo "domains.txt found at: $DOMAINS_FILE"
          echo "File contents:"
          cat "$DOMAINS_FILE"
        else
          echo "domains.txt not found"
        fi
    - name: Process domains
      run: go run process_domains.go

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add vmess_list.txt trojan_list.txt
        git commit -m "Update proxy lists" || echo "No changes to commit"
        git push
